kind: pipeline
type: ssh
name: default


# 指定构建服务器
server:
  host: tx.chenyn.cn
  #user: chenyn
  user:
    from_secret: username
  password:
    from_secret: password


#指定对那个分支什么行为构建
trigger:
  branch:
    - master
  event:
    - tag

# 关闭clone
clone:
  disable: true

steps:
  - name: clone
    commands:
      - git init
      - git remote add origin git@github.com:chenyn-java/ems-jsp.git
      #- git fetch --all
      - git pull origin ${DRONE_BRANCH}

  - name: build
    commands:
      - docker build -t ems-jsp:1.0 .

  - name: run
    commands:
      - export SERVICE_DIR=/home/chenyn/services/ems
      - mkdir -p $${SERVICE_DIR}
      - docker-compose down apps
      - sleep 5s
      - docker-compose up -d