kind: pipeline
type: ssh
name: default


server:
  host: tx.chenyn.cn
  #user: chenyn
  user:
    from_secret: username
  #password: Xiao618%
  password:
    from_secret: password

steps:
  - name: build
    commands:
      - echo "i am xiaochen"
      - echo "i am xiaoming"