kind: pipeline
type: ssh
name: default


# 指定构建服务器
server:
  host: tx.chenyn.cn
  #user: chenyn
  user:
    from_secret: username
  #password: Xiao618%
  password:
    from_secret: password


#指定对那个分支什么行为构建
trigger:
  branch:
    - master
  event:
    - tag

# 关闭clone
clone:
  disable: true

steps:
  - name: clone
    commands:
      - git clone git@github.com:chenyn-java/ems-jsp.git
      - ls .
#  - name: build
#    environment:
#      EMS_IMAGE: ems-jsp:${DRONE_TAG##v}
#    commands:
#      - docker build -t $EMS_IMAGE .