kind: pipeline
type: ssh
name: default


# 指定构建服务器
server:
  host: tx.chenyn.cn
  #user: chenyn
  user:
    from_secret: username
  #password: Xiao618%
  password:
    from_secret: password


#指定对那个分支什么行为构建
trigger:
  branch:
    - master
  event:
    - tag

steps:
  - name: clone
    commands:
      - git init
      - git remote add origin ${DRONE_GIT_SSH_URL}
      - git fetch origin +refs/tags/${DRONE_TAG}
      - git pull origin ${DRONE_BRANCH}