kind: pipeline
type: ssh
name: default


server:
  host: tx.chenyn.cn
  user: chenyn
  password: xiao618%

steps:
  - name: build
    commands:
      - echo "i am xiaochen"
      - echo "i am xiaoming"