server:
  port: 8989
  servlet:
    context-path: /ems-jsp
    jsp:
      init-parameters:
        development: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems-jsp?characterEncoding=UTF-8
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .jsp

mybatis:
  mapper-locations: classpath:com/baizhi/emsjsp/mapper/*.xml
  type-aliases-package: com.baizhi.emsjsp.entity



